// CLIENTS
export const SET_ACTIVE_CLIENT = 'SET_ACTIVE_CLIENT';
export const SET_ACTIVE_CLIENT_NAME = 'SET_ACTIVE_CLIENT_NAME';
export const SET_ACTIVE_CLIENT_ADDRESS = 'SET_ACTIVE_CLIENT_ADDRESS';
export const CLEAR_ACTIVE_CLIENT = 'CLEAR_ACTIVE_CLIENT';

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';

export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILURE = 'UPDATE_CLIENT_FAILURE';

export const REMOVE_CLIENT = 'REMOVE_CLIENT';
export const REMOVE_CLIENT_SUCCESS = 'REMOVE_CLIENT_SUCCESS';
export const REMOVE_CLIENT_FAILURE = 'REMOVE_CLIENT_FAILURE';

export const IMPORT_CLIENTS = 'IMPORT_CLIENTS';
export const IMPORT_CLIENTS_SUCCESS = 'IMPORT_CLIENTS_SUCCESS';
export const IMPORT_CLIENTS_FAILURE = 'IMPORT_CLIENTS_FAILURE';
export const CACHE_CLIENT_IMPORTS = 'CACHE_CLIENT_IMPORTS';
export const CLEAR_CLIENT_IMPORTS = 'CLEAR_CLIENT_IMPORTS';

// EMPLOYEES
export const SET_ACTIVE_EMPLOYEE = 'SET_ACTIVE_EMPLOYEE';
export const SET_ACTIVE_EMPLOYEE_FIRSTNAME = 'SET_ACTIVE_EMPLOYEE_FIRSTNAME';
export const SET_ACTIVE_EMPLOYEE_LASTNAME = 'SET_ACTIVE_EMPLOYEE_LASTNAME';
export const SET_ACTIVE_EMPLOYEE_EMAIL = 'SET_ACTIVE_EMPLOYEE_EMAIL';
export const CLEAR_ACTIVE_EMPLOYEE = 'CLEAR_ACTIVE_EMPLOYEE';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEES_FAILURE';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAILURE = 'UPDATE_EMPLOYEE_FAILURE';

export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS';
export const REMOVE_EMPLOYEE_FAILURE = 'REMOVE_EMPLOYEE_FAILURE';

export const IMPORT_EMPLOYEES = 'IMPORT_EMPLOYEES';
export const IMPORT_EMPLOYEES_SUCCESS = 'IMPORT_EMPLOYEES_SUCCESS';
export const IMPORT_EMPLOYEES_FAILURE = 'IMPORT_EMPLOYEES_FAILURE';
export const CACHE_EMPLOYEE_IMPORTS = 'CACHE_EMPLOYEE_IMPORTS';
export const CLEAR_EMPLOYEE_IMPORTS = 'CLEAR_EMPLOYEE_IMPORTS';

// HISTORY
export const GET_HISTORY = 'GET_HISTORY';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE';

// ETC
export const ZERO_DATABASE = 'ZERO_DATABASE';
export const ZERO_DATABASE_SUCCESS = 'ZERO_DATABASE_SUCCESS';
export const ZERO_DATABASE_FAILURE = 'ZERO_DATABASE_FAILURE';
