export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';

export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILURE = 'UPDATE_CLIENT_FAILURE';

export const SET_ACTIVE_CLIENT = 'SET_ACTIVE_CLIENT';
export const SET_ACTIVE_CLIENT_NAME = 'SET_ACTIVE_CLIENT_NAME';
export const SET_ACTIVE_CLIENT_ADDRESS = 'SET_ACTIVE_CLIENT_ADDRESS';
export const CLEAR_ACTIVE_CLIENT = 'CLEAR_ACTIVE_CLIENT';
